### ISSUE TITLE
Can the value_from function add iterator parameters, such as value_from (Iterator begin, Iterator end)

### ISSUE THREAD

**Issue by wcy168** [boostorg/json#1000]
PLEASE DON'T FORGET TO "STAR" THIS REPOSITORY :)

When reporting a bug please include the following:

### Version of Boost

You can find the version number in the file `<boost/version.hpp>`

### Steps necessary to reproduce the problem

A small compiling program is the best. If your code is
public, you can provide a link to the repository.

### All relevant compiler information

If you are unable to compile please include the type and
version of compiler you are using as well as all compiler
output including the error message, file, and line numbers
involved.

The more information you provide the sooner your issue
can get resolved!

**Comment by grisumbras** [comment]
You didn't explain the desired semantics, so I assume it's supposed to produces a `json::value` that stores an `array`. So, my questions are these.  Why converting a sequence object doesn't work for you? Where do you get the iterators?

**Comment by wcy168** [comment]
> 你没有解释所需的语义，所以我认为它应该产生一个存储 .所以，我的问题是这些。为什么转换序列对象对您不起作用？你从哪里得到迭代器？`json::value``array`

Due to the large amount of data in my sequential container, I can only send a part of it at a time. Therefore, I need to serialize just this portion, so I expect to transmit the iterator range.

**Comment by wcy168** [comment]
> You don't have the required semantics to explain, so I think it should produce a store. Why doesn't converting sequence objects work for you? Where do you get iterators?`json::value``array`

Due to the large amount of data in my sequential container, I can only send a part of it at a time. Therefore, I need to serialize just this portion, so I expect to transmit the iterator range.

**Comment by grisumbras** [comment]
But can't you wrap two iterators into a range-like class? This one should work: https://www.boost.org/doc/libs/1_85_0/libs/range/doc/html/range/reference/utilities/iterator_range.html
But if you have access to C++20, this should also work: https://en.cppreference.com/w/cpp/ranges/subrange

**Comment by wcy168** [comment]
> But can't you wrap two iterators into a range-like class? This one should work: https://www.boost.org/doc/libs/1_85_0/libs/range/doc/html/range/reference/utilities/iterator_range.html But if you have access to C++20, this should also work: https://en.cppreference.com/w/cpp/ranges/subrange

good idea，thank you

**Comment by grisumbras** [comment]
Silentium videtur confessio.
