### ISSUE TITLE
object hash function should be order-independent

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#1059]
I think the only way to correctly calculate the hash is to first sort the elements by key into a temporary array.

**Comment by grisumbras** [comment]
Currently we defer to ContainerHash which does support hashing of unordered containers. It does so correctly (that is, equal containers produce the same hashes), but there's the question if the algorithms produces too many collisions. Are we concerned with that possibility? Performance-wise, we are unlikely to get anything better.

**Comment by vinniefalco** [comment]
I was wrong... you don't have to sort. You can calculate the digest of each element and add them up together, like Hash2 does in `hash_append_unordered_range`.
