### ISSUE TITLE
value::visit() function?

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#207]
This would be easy to implement, do we need it? Should we just make it an example?

**Comment by sdkrystian** [comment]
This can wait until it is requested by a user

**Comment by vinniefalco** [comment]
it would just be an example anyway, the bar is lower for that

**Comment by brooksprumo** [comment]
I ended up asking y'all in Slack on how to do basically just this. If the bar is still low to make an example, I think this would likely be very useful to new clients (at least it would've been for me).
