### ISSUE TITLE
is_valid_utf8

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#251]
This could be of use
```
bool is_valid_utf8( string_view s);
```

**Comment by vinniefalco** [comment]
This one could return `s` or throw:
```
string_view valid_utf8( string_view s );
```

**Comment by sdkrystian** [comment]
You couldn't have both though. I prefer the first.

**Comment by vinniefalco** [comment]
Of course you can have both. The first one is good, but so is the second one, as you can use it in expressions:
```
value jv = valid_utf8( "\xff" ); // throws
```

**Comment by vinniefalco** [comment]
Nothing actionable here yet

**Comment by pdimov** [comment]
I would expect a function returning string_view to return the longest valid UTF-8 prefix, not identity.

**Comment by sdkrystian** [comment]
You can't have both; functions cannot be overloaded based on return type.

**Comment by grisumbras** [comment]
Is this in scope, though?

**Comment by vinniefalco** [comment]
No one has asked, so no
