### ISSUE TITLE
Incorrect documentation on multiple members with same key

### ISSUE THREAD

**Issue by beached** [boostorg/json#278]
The document http://develop.json.cpp.al/json/ref/boost__json__object/object/overload4.html says that the first is kept, but my understanding is the the last is kept

**Comment by vinniefalco** [comment]
>If there are elements with duplicate keys, that is, if multiple elements in the range have keys that compare equal, only the last equivalent element will be inserted.

**Comment by vinniefalco** [comment]
parser and value_stack need similar treatment, and we should probably also mention it in the exposition, under "Using Objects"

**Comment by vinniefalco** [comment]
This should be fixed now.
