### ISSUE TITLE
Tables should be aligned to element type

### ISSUE THREAD

**Issue by sdkrystian** [boostorg/json#293]
e.g. `object_impl::table` should be aligned to `alignof(key_value_pair)`

**Comment by vinniefalco** [comment]
need a static assert that the integer array which follows the key value pairs is also aligned

**Comment by vinniefalco** [comment]
`array` is fixed

**Comment by vinniefalco** [comment]
`object` is correct now

**Comment by vinniefalco** [comment]
That's the last of it, strings don't need alignment.
