### ISSUE TITLE
Smaller pow10

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#353]
Using Peter's code we can use up less space in the implementation of pow10

**Comment by grisumbras** [comment]
Source?

**Comment by vinniefalco** [comment]
@pdimov ? Where was that godbolt example you wrote?

**Comment by pdimov** [comment]
Somewhere in the archive of #boost-json I'd assume. I no longer recall what was in it.

**Comment by grisumbras** [comment]
@vinniefalco do you remember what was in it?

**Comment by sdkrystian** [comment]
Here is Peter's reference implementation: https://godbolt.org/z/K4cx6z

Here is my version of it: https://godbolt.org/z/Pj71GG

**Comment by grisumbras** [comment]
Thanks!

**Comment by grisumbras** [comment]
I think, this should be closed. The approach we use currently results in higher precision.

**Comment by vinniefalco** [comment]
Close it
