### ISSUE TITLE
Proper Documentation file is needed

### ISSUE THREAD

**Issue by siddharth25pandey** [boostorg/json#362]
For the new comers, it is very difficult to implement the libraries without having proper documentation about the workflow,Advantages, how to use, features.
Also, proper guide how to get started with Awesome Library so, that it will be useful for normal man.

**Comment by vinniefalco** [comment]
There's a link to the documentation right in the README.md: https://master.json.cpp.al/

**Comment by siddharth25pandey** [comment]
I gone through the README.md file but it is not user-friendly. Also it lacks the following
* Workflow
* Feature/methods
* Example for new user how to implement it in their C++ file
* Video tutorial is high useful.

**Comment by vinniefalco** [comment]
Did you read this? https://master.json.cpp.al/

**Comment by siddharth25pandey** [comment]
@vinniefalco Yeah I read this & also gone through the attached PDF also.
From my opinion, the link you provided haven't satisfy the need of the new-bie user and the document that is attached with it is lack of examples of different functionalities.
Better to create a new Document.md file which consists of the leftover specifications that are necessary to go on.
Thanks!

**Comment by vinniefalco** [comment]
> the link you provided haven't satisfy the need of the new-bie user and the document that is attached with it is lack of examples of different functionalities.

So you saw this page then? https://master.json.cpp.al/json/usage/quick_look.html

**Comment by siddharth25pandey** [comment]
@vinniefalco Yeah that is absolutely fine but the link should be present in README file. So, that new users have a quick glance of the things in one sight.

**Comment by vinniefalco** [comment]
The README.md should link to the built boost documentation when it becomes part of the superproject

**Comment by siddharth25pandey** [comment]
@vinniefalco So, what shall I do now?

**Comment by grisumbras** [comment]
I've looked through README again and compared it with [Standard Readme spec](https://github.com/RichardLitt/standard-readme/blob/master/spec.md). Although our readme isn't complaint, we have pretty much all of the information required. The only thing, IMO, how it could be improved, is a link to the docs  somewhere close to the beginning (even though we have that already in project description). So, I'm closing this issue.
