### ISSUE TITLE
init-list ctor javadocs

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#379]
The reference for the initializer_list constructor could use some improvements: e.g. "Construct an object or array from an initializer_list". I find this hugely important since just the mere presence of an initializer_list constructor changes the meaning of brace initialization.

**Comment by grisumbras** [comment]
[The current javadoc](https://www.boost.org/doc/libs/1_79_0/libs/json/doc/html/json/ref/boost__json__value/value/overload35.html#json.ref.boost__json__value.value.overload35.description) is a bit more specific, do we still need this issue?
