### ISSUE TITLE
array ctor javadoc

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#387]
The initializer_list constructor for array is listed under move constructors.

**Comment by vinniefalco** [comment]
This looks like a docca problem because the brief says "Constructor." But it is listed under "Move constructors."

**Comment by vinniefalco** [comment]
![image](https://user-images.githubusercontent.com/1503976/94327256-85802d00-ff5e-11ea-86a8-87302944629a.png)

**Comment by evanlenz** [comment]
This should be fixed now as a result of merging boostorg/docca#42.

**Comment by evanlenz** [comment]
This should be fixed once we close https://github.com/boostorg/docca/pull/46

**Comment by vinniefalco** [comment]
Yep, fixed
