### ISSUE TITLE
basic_parser javadoc example

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#395]
The basic_parser reference documentation would benefit from either a link to an example or an inline example.

**Comment by grisumbras** [comment]
We could link to Validate example. Or do we need something more interesting?

**Comment by vinniefalco** [comment]
validate is sufficient but I don't think you can link to it because of toolchain limitations so I think maybe we can close this.

**Comment by grisumbras** [comment]
Managed to do it (https://705.jsondocs.prtest.cppalliance.org/libs/json/doc/html/json/ref/boost__json__basic_parser.html#json.ref.boost__json__basic_parser.see_also).
Albeit, in a hacky way (https://github.com/boostorg/json/pull/705/files#diff-b3f570c24765f07f3fe586b12fe7a0f35f9cdcec9fafd8cf22b57c3fb7eca37eR267-R268)
