### ISSUE TITLE
json::string convert to std::string

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#406]
Might be nice to have `string::to_std_string` although this means including `<string>`.

**Comment by grisumbras** [comment]
1. `core/detail/string_view.hpp` includes `<string>` so, not including it in JSON is moot.
2. `std::string s = json::string_view(json::string());` works. And with C++17 `auto s = std::string(json::string());` also works. Is this good enough?

**Comment by vinniefalco** [comment]
Given
```
json::string js;
```

My intuition tells me that users want the expression `js.to_string()` (alternatively: `js.to_std_string()`) to return a `std::string`. This clearly expresses intent and can be searched. But I could be convinced otherwise. What is typical practice here?

**Comment by grisumbras** [comment]
QString has toStdString, but I don't think Qt is the best example of model C++ API. I'm personally perfectly Ok with a conversion (even though it's a bit obscure in C++11 mode). So, let's keep the issue for now and see if users actually ask for a dedicated conversion function.

**Comment by vinniefalco** [comment]
I would prefer if users simply worked with the native `json::string` since that is the most efficient. Making it easy to convert to `std::string` only encourages inefficiency.

**Comment by grisumbras** [comment]
Still no issues about this. I'm inclined to close this.
