### ISSUE TITLE
Using Strings exposition

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#412]
This section needs a rewrite. It should explain how the string works including the small buffer optimization, differences from std::string and the ability to access capacity beyond size.

**Comment by DhairyaBahl** [comment]
I would like to work on this issue. Kindly assign it to me .

Thanks :)

**Comment by vinniefalco** [comment]
You can work on it regardless of who it is assigned to.. just submit a pull request with your proposed changes.

**Comment by DhairyaBahl** [comment]
@vinniefalco Okay I got it . Thanks :)

**Comment by DhairyaBahl** [comment]
@vinniefalco Can you tell me which section you were talking about in the issue description. Kindly explain the issue in detail .

Thanks :)
