### ISSUE TITLE
private friends in detail namespace are visible

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#417]
![image](https://user-images.githubusercontent.com/1503976/94327138-ef4c0700-ff5d-11ea-8cf3-5fd2d43434be.png)

**Comment by evanlenz** [comment]
I can't seem to reproduce this one. Is there another example? Has it been fixed in the source? Or just worked around?

**Comment by vinniefalco** [comment]
We owe you a reproducible test case so we will add it to the examples, once it is working

**Comment by vinniefalco** [comment]
This got moved, thanks
