### ISSUE TITLE
Constructors with the same brief are not always grouped together

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#440]
![image](https://user-images.githubusercontent.com/1503976/95005229-67dc4480-05aa-11eb-83d2-976404f54833.png)

**Comment by evanlenz** [comment]
It looks like the Doxygen output has the memberdefs grouped into three separate <sectiondef> elements:

<sectiondef kind="user-defined">...</sectiondef>
<sectiondef kind="user-defined">...</sectiondef>
<sectiondef kind="public">...</sectionef>

Do you know what causes these? The current XSLT only de-duplicates within the sectiondef, not across sectiondefs. It sounds like we may want to essentially ignore these for purposes of rendering the overload-list page.

**Comment by vinniefalco** [comment]
Moved to https://github.com/boostorg/docca/issues/44
