### ISSUE TITLE
Consider using the same atomic ops as boost::shared_ptr` does.

### ISSUE THREAD

**Issue by maximilianriemensberger** [boostorg/json#444]
https://github.com/boostorg/json/blob/5098730a87148228f65b2dcb40ecec7f15019c09/include/boost/json/storage_ptr.hpp#L108

`boost::json::storage_ptr` uses sequentially consistent atomic ops for the reference count. This is needlessly expensive on most non-x86 platforms, in particular arm and the like. `boost::shared_ptr` apparently implements more efficient reference counting (usually relaxed inc + acquire release dec). Considering that there's one `storage_ptr` per `value`, that's potentially quite a large number of incs and decs for a large json document. I would suggest that `storage_ptr` reference count operations match those of `boost::shared_ptr`.

**Comment by vinniefalco** [comment]
If you want to submit a pull request, I'm more than happy to merge it. Or I can do it. To be honest though, I don't know much about atomic operations except how to write `std::atomic<...>` and use it in the simplest fashion.

**Comment by vinniefalco** [comment]
we might want `storage()` to return `storage_ptr const&` again

**Comment by maximilianriemensberger** [comment]
> we might want `storage()` to return `storage_ptr const&` again

That definitely saves some ref count ops.

**Comment by maximilianriemensberger** [comment]
> If you want to submit a pull request, I'm more than happy to merge it. Or I can do it. To be honest though, I don't know much about atomic operations except how to write `std::atomic<...>` and use it in the simplest fashion.

I can look into it.

**Comment by madmongo1** [comment]
Getting atomic ops right beyond using sequential consistency is *hard*. Strongly suggest a review by more than one person if this route is taken (which it should be in order to make pool-based operations more competitive).

**Comment by vinniefalco** [comment]
well, I _think_ just copying ` boost::shared_ptr` is a no-lose proposition

**Comment by madmongo1** [comment]
@maximilianriemensberger  Looking at the design of storage_ptr, it would seem that `boost::instrusive_ptr` would be a better model.

https://www.boost.org/doc/libs/1_74_0/libs/smart_ptr/doc/html/smart_ptr.html#intrusive_ptr

https://github.com/boostorg/smart_ptr/blob/develop/include/boost/smart_ptr/detail/atomic_count.hpp

@pdimov - your view?

**Comment by vinniefalco** [comment]
`storage_ptr` is already modeled after `intrusive_ptr`. It manages an object whose reference counts are in the object itself. Or did you mean something else?

**Comment by madmongo1** [comment]
I meant that the atomic modification of intrusive_ptr reference counts already has careful treatment in the smart_ptr library.
It's different for each compiler/platform because of differences in intrisics and differences in the natural atomic strength of operations on different processors.
e.g. Arm is a lot more fussy than x86 (which is basically bomb proof)

**Comment by maximilianriemensberger** [comment]
I totally agree that there should be many eyes looking any atomic ops things. #446 is what I think is sufficient. It is what libc++ uses for its shared_ptr implementation (just uglyfied and with intrinsics). I have yet to check the other std libs. 

boost::smart_ptr does acq_rel incfrement and decrement instead of relaxed increment and acq_rel decrement. That made me scratch my head. But may @pdimov can shed some light onto this issue.

Anyway I think you should definitely only merge changes to the refcount here after careful review and consideration. Stealing from widely used and reviewed refcount implemenetations (stdlib/boost/...) seems like a good idea nevertheless.

**Comment by madmongo1** [comment]
I concur. The increment can be merely atomic because there is no dependency on the value after the increment.
On the other hand the decrement can result in the destruction of the object so it must be acquire (to get the previous value) and release (to communicate the new value to other threads).

**Comment by pdimov** [comment]
>boost::smart_ptr does acq_rel incfrement and decrement instead of relaxed increment and acq_rel decrement.

Does it? Where?

**Comment by maximilianriemensberger** [comment]
> > boost::smart_ptr does acq_rel incfrement and decrement instead of relaxed increment and acq_rel decrement.
> 
> Does it? Where?

I think I incorrectly tracked the implementation down to the `atomic_count` headers, which use acq_rel inc and acq_rel dec. Instead I should have looked at sp_counted_base_std_atomic instead. Sorry for the confusion.

**Comment by pdimov** [comment]
IIRC the atomic_count headers conservatively use acq_rel because you could, technically, use a negative count and swap the meanings of increment and decrement in your code.

**Comment by vinniefalco** [comment]
This is done, thanks!
