### ISSUE TITLE
Document that JSON's default resource is always new_delete_resource

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#458]
The allocators Background needs to compare and contrast std's `get_default_resource` which accesses a global, mutable state with Boost.JSON's approach of making the default resource always a `new_delete_resource`. At the same time we can change these lines:

```
// This vector will use the default memory resource
std::vector< value, polymorphic_allocator < value > > v;
```

to no longer indirectly call `get_default_resource` (which causes a link error)

**Comment by grisumbras** [comment]
[This](https://www.boost.org/doc/libs/1_79_0/libs/json/doc/html/json/allocators/storage_ptr.html) mentions that by default `storage_ptr` references a memory resource that is equivalent to using new and delete. Do we need something more elaborate or the issue could be closed?

**Comment by vinniefalco** [comment]
Its good enough
