### ISSUE TITLE
gcc 4.8 is not supported

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#491]
gcc-4.8.x is not supported, because it has incomplete C++11 support. The documentation and README.md need to be updated to reflect this, as well as the CI scripts. Alternatively, we can make it work.

**Comment by vinniefalco** [comment]
This is actually a problem with Boost.Config erroneously reporting that `alignas` is not available on gcc-4.8.5 (and possibly earlier)

**Comment by grisumbras** [comment]
Boost.Config appears to correctly consider GCC 4.8 to _not_ support `alignas`, because it has bugs. Those bugs do not affect Boost.Json, though. We have to use a custom check.

**Comment by grisumbras** [comment]
Commit dd7c77d fixes this issue.
