### ISSUE TITLE
BOOST_SYMBOL_VISIBLE?

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#496]
The boost developer's mailing list thread with subject "[boost] Wrong class export/visibility setting for shared libs in many Boost libs" might be actionable and should be investigated.

**Comment by grisumbras** [comment]
This comment describes what uses are affected:  https://github.com/boostorg/config/issues/362#issuecomment-771855999
I've looked through the project and I don't think we have any of those.

**Comment by vinniefalco** [comment]
we can close it I guess?
