### ISSUE TITLE
Why does read_json(..) throw exception for utf-8 stringstream from string?

### ISSUE THREAD

**Issue by dkd1111** [boostorg/json#503]
```
/*CODE_1*/
boost::beast::http::response<boost::beast::http::string_body> &&res
...
std::stringstream ss;
ss << res.body();
boost::property_tree::ptree tree{};
boost::property_tree::read_json(ss, tree);
```
CODE_1 is fine.

```
/*CODE_2*/
boost::beast::http::response<boost::beast::http::string_body> &&res
...
std::stringstream ss;
ss << res.body();
std::string msg = ss.str();
ss.clear();
ss << msg;
boost::property_tree::ptree tree{};
boost::property_tree::read_json(ss, tree);
```
CODE_2 throws exception("garbage after data").

Variable "ss" is encoded utf-8.
Why does read_json(..) throw exception for utf-8 stringstream from string?

**Comment by vinniefalco** [comment]
> Why does read_json(..) throw exception for utf-8 stringstream from string?

`read_json` is from Boost.PropertyTree, not Boost.JSON. You are using the wrong library. If you want to use Boost.JSON you need to use `boost::json::parse`. See:

https://www.boost.org/doc/libs/develop/libs/json/doc/html/index.html

**Comment by dkd1111** [comment]
ok. thanks.
