### ISSUE TITLE
Release prep

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#512]
We need the release notes for the website:
https://github.com/boostorg/website/blob/master/feed/history/boost_1_76_0.qbk
Please submit as a pull request to that repo, marked as Draft, and tag @vinniefalco in it so I can review.

If there are very few changes we can inline them into the website. Otherwise we should point users to a new page in the documentation with a changelog, in the style of Beast.

We should probably add a CHANGELOG.md to the repo.

**Comment by grisumbras** [comment]
We can merge documentation updates to master now.
