### ISSUE TITLE
value('a').is_int64()

### ISSUE THREAD

**Issue by doganulus** [boostorg/json#525]
I would expect `value('a').kind()` to be a `string` but it is `int64`. Bug or feature?

**Comment by grisumbras** [comment]
That's an interesting question. @vinniefalco ?

**Comment by grisumbras** [comment]
> Vinnie: value( "a" ) is a string. value( 'a' ) is not. Working as intended
So, not a bug.

**Comment by WPMGPRoSToTeMa** [comment]
Probably `value` with a char-type argument should be prohibited (`delete`d) to avoid any surprising behavior to users?

**Comment by vinniefalco** [comment]
> Probably value with a char-type argument should be prohibited (deleted) to avoid any surprising behavior to users?

I'm not opposed to it although I am not an expert. Maybe try submitting a pull request and see what CI thinks about it?

**Comment by vinniefalco** [comment]
Unfortunately it looks like this is a corner case of C++ where there is no perfect solution.

**Comment by WPMGPRoSToTeMa** [comment]
> 
> 
> Hmm... come to think of it, deleting that constructor would break conversion from `int8`, which is allowed to be an alias for `char`.

Yep, it is true on `AArch64` (https://reviews.llvm.org/D85225)...

**Comment by vinniefalco** [comment]
Working as designed, this is the best we can do with the current specification of C++.
