### ISSUE TITLE
Can't compile with boost

### ISSUE THREAD

**Issue by AnthonySabbagh** [boostorg/json#539]
### Version of Boost

1_75

### Steps necessary to reproduce the problem

json.cpp
```
#include <boost/json.hpp>

int main(){
    boost::json::parser p;
    return 0;
}

```
If I try to compile this with g++ -std=c++11 -o json json.cpp, I get the following errors:
```
/usr/bin/ld: /tmp/cc8D7xCy.o: in function `boost::json::detail::handler::~handler()':
json.cpp:(.text._ZN5boost4json6detail7handlerD2Ev[_ZN5boost4json6detail7handlerD5Ev]+0x18): undefined reference to `boost::json::value_stack::~value_stack()'
/usr/bin/ld: /tmp/cc8D7xCy.o: in function `boost::json::basic_parser<boost::json::detail::handler>::~basic_parser()':
json.cpp:(.text._ZN5boost4json12basic_parserINS0_6detail7handlerEED2Ev[_ZN5boost4json12basic_parserINS0_6detail7handlerEED5Ev]+0x1c): undefined reference to `boost::json::detail::stack::~stack()'
/usr/bin/ld: /tmp/cc8D7xCy.o: in function `boost::json::parser::parser()':
json.cpp:(.text._ZN5boost4json6parserC2Ev[_ZN5boost4json6parserC5Ev]+0x5e): undefined reference to `boost::json::parser::parser(boost::json::storage_ptr, boost::json::parse_options const&)'
collect2: error: ld returned 1 exit status
```
### All relevant compiler information

gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 

I have boost 1.75.0 in my usr/include folder. I am able to use the beast library with no issue, but I can't compile programs that use the json library. What am I doing wrong?

**Comment by beached** [comment]
I think you need to add -Lboost_json to link to boost json or include #include <boost/json/src.hpp> also so that it's header only

**Comment by vinniefalco** [comment]
That's a link error, not a compiler error.

**Comment by grisumbras** [comment]
Since you do not link to the library, this is header-only usage variant. Which is documented [here](https://www.boost.org/doc/libs/1_75_0/libs/json/doc/html/json/overview.html#json.overview.requirements.header_only). In other words, see @beached's comment above.

**Comment by AnthonySabbagh** [comment]
Thanks guys. I got the header only option to work. I am quite a noob with linking. IDK if this is the best place to ask, but how would I get the other option working (linking to boost json). I still get the same linking errors when I try to compile with the linker option -Lboost_json. I'm guessing I have to compile something first (which I didn't do)?

**Comment by vinniefalco** [comment]
Have you ever linked a library before?

**Comment by AnthonySabbagh** [comment]
Only really simple stuff for learning. I think I understand it now after looking more into it.
