### ISSUE TITLE
Best way to check if key exists?

### ISSUE THREAD

**Issue by KordianD** [boostorg/json#579]
What is the best way to check if a given key exists in json?

Json example

    {
        "1":{
           "key":"A"
        }
     }

I want to parse key `missingKey` but I do not know whether it exists in json. 

    #include <string>
    #include <boost/json/src.hpp>

    int main() {

        const std::string json = "{"
                                 "\"1\":{"
                                 "\"key\": 10"
                                 "}}";

       const boost::json::value jv = boost::json::parse(json);
       const boost::json::object& rootJsonObject = jv.as_object();

       for (const auto& jsonIdRoot : rootJsonObject)
       {
         const auto& jsonObject = jsonIdRoot.value();
         jsonObject.at("missingKey").as_int64();
       } 
    }

This will throw exception because "missingKey" is missing. 

Is there any exists/contains etc method to do this?

**Comment by vinniefalco** [comment]
This is one easy way:

https://www.boost.org/doc/libs/develop/libs/json/doc/html/json/ref/boost__json__object/if_contains.html
```
if( p = jsonObject.if_contains( "missingKey" ) )
```

You could also use `object::find`
https://www.boost.org/doc/libs/develop/libs/json/doc/html/json/ref/boost__json__object/find/overload1.html

**Comment by grisumbras** [comment]
@KordianD does Vinnie's comment answer your question?
