### ISSUE TITLE
Consider using std::error_condition rather than std::error_code

### ISSUE THREAD

**Issue by accelerated** [boostorg/json#585]
`std::error_code` is not platform independent. Since this is a generic json library, I don't see a particular reason for not using platform-independent `std::error_condition`.

**Comment by vinniefalco** [comment]
Beast and Asio use `error_code`. Maybe `error_condition` is more correct (@pdimov ?), maybe not - but if Boost.JSON uses a different type then the user experience would be impacted.

**Comment by accelerated** [comment]
@vinniefalco I think running as JSON_STANDALONE gives you the proper conversions...currently looking into it, as there are too many type conversion friction points. If Asio uses error_code then perhaps it's better to stick to that. It's just a suggestion. The whole error_code vs error_condition is quite confusing for everyone, myself included. Supposedly error_condition is meant to categorize the platform-specific error_codes.

**Comment by vinniefalco** [comment]
> The whole error_code vs error_condition is quite confusing for everyone

Confusing for me as well.

Can you find any examples of open source libraries (perhaps on GitHub) which use `error_condition&` in their public interfaces to return errors?

**Comment by grisumbras** [comment]
https://eel.is/c++draft/syserr.errcondition#overview-1
> The class error_­condition describes an object used to hold values identifying error conditions.
> [Note 1: error_­condition values are portable abstractions, while error_­code values ([syserr.errcode]) are implementation specific. — end note]

There's nothing in the standard about platform dependence, only about specificity. Apparently, cppreference says `error_condition` is about platform-independence. Well, it's not entirely correct.

Our `error_code`s describe specific situations which prevent the functions to produce a result. Our `error_condition`s describe higher level errors: parsing error or  conversion error.

Interesting reading:
http://blog.think-async.com/2010/04/system-error-support-in-c0x-part-5.html
https://akrzemi1.wordpress.com/2017/07/12/your-own-error-code/

**Comment by grisumbras** [comment]
I guess, the simplest approach to describing the difference is this: libraries (including the standard library) give users `error_code`s. User can disregard specificity and convert those to `error_condition`s that group similar error codes coming from a library, or coming from several similar libraries (useful in software that deals with devices or services from different vendors), or coming from different implementations of the same library (e.g. the standard library on different OSes).

**Comment by vinniefalco** [comment]
Boost.JSON does use the groupings, and comparisons work:
https://www.boost.org/doc/libs/develop/libs/json/doc/html/json/ref/boost__json__condition.html

**Comment by pdimov** [comment]
> Maybe `error_condition` is more correct

No, it isn't. Functions should never return errors using `error_condition`, only with `error_code`. `error_condition` is _only_ for comparing codes to.
