### ISSUE TITLE
No simple way to parse from std::istream

### ISSUE THREAD

**Issue by grisumbras** [boostorg/json#619]
There should be a quick and convenient way to parse JSON from `std::istream`. E.g. 
```c++
std::ifstream f("path/to/file");
auto jv = json::parse(f);
```

**Comment by vinniefalco** [comment]
> there should be parse_istream and there should even be parse_file that takes the file name directly

Well, `parse_istream` can just be a `parse` overload.

**Comment by vinniefalco** [comment]
@prince-chrismc I agree! Would you like to try your hand at it? Shouldn't be too hard...

**Comment by grisumbras** [comment]
I have a blueprint for the fix. I originally wanted to make the streambuffer to put all input into parser as soon as possible which would work OK with something like `istream >> &json_buffer`. But then I realized that
```c++
std::copy(
  std::istreambuf_iterator<char>(istream),
  std::istreambuf_iterator<char>(),
  std::ostreambuf_iterparsing(&json_buffer))
```
will push input into parser one byte a time, which is very ineffective.
So, my approach has to be changed to have a  proper buffer in the streambuf.
