### ISSUE TITLE
No support for JSON pointer syntax

### ISSUE THREAD

**Issue by LeonineKing1199** [boostorg/json#622]
Similar libraries such as nlohmann's or RapidJSON support access to values via the [JSON pointer](https://datatracker.ietf.org/doc/html/rfc6901) syntax.

Boost.JSON should have feature parity in this regard, perhaps introducing `value:at_p(string_view)` member function.

**Comment by vinniefalco** [comment]
Duplicate of https://github.com/boostorg/json/issues/480
