### ISSUE TITLE
Deprecate Standalone for 1.78

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#628]
When standalone is defined we need to generate a warning message for 1.78. Then in 1.79 we will remove it (after forking it to a new repository on https://github.com/CPPAlliance)

**Comment by doganulus** [comment]
How would you continue to develop then? Develop on standalone continuously and integrate/snapshot on Boost releases?

**Comment by vinniefalco** [comment]
Well they would diverge. Some features might be ported but it is doubtful, because Boost offers facilities that are not available in C++17. For example, mp11. And Describe. A better `error_code` with source-file information. And other things. Keeping standalone features on parity with Boost.JSON means that the library cannot improve as much.
