### ISSUE TITLE
debug visualizer for gcc (and/or clang)

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#644]
Similar to json.natvis

**Comment by grisumbras** [comment]
https://sourceware.org/gdb/current/onlinedocs/gdb/Pretty-Printing.html#Pretty-Printing

**Comment by grisumbras** [comment]
Examples:
https://undo.io/resources/gdb-watchpoint/debugging-pretty-printers-gdb-part2/
https://github.com/nlohmann/json/issues/1952

**Comment by grisumbras** [comment]
Implemented in #733.
