### ISSUE TITLE
Adding [] operator to json::value?

### ISSUE THREAD

**Issue by byeonghyeonyou** [boostorg/json#662]
It would be great if json::value had [] operator.
If there is the [] operator in json::value, it will be far more convenient to access subelements.

Currently we can access a subelement with at() such as `value.at("key1").at(0).at("key2")`. It is more verbose and less readable than `value["key1"][0]["key2"]`.
Proxy example provides [] operator, but using Proxy causes another difficulty. We need to construct Proxy object and then dereference it with json::value just to access the element(`(*Proxy(value)["key1"][0]["key2"]).as_int64()`).

If json::value had [] operator, we can handle this more easily: `value["key1"][0]["key2"].as_int64()`.

Would it be okay if I try adding it?

**Comment by vinniefalco** [comment]
That's never going to happen

**Comment by grisumbras** [comment]
We're planning to add support for JSON Pointer in the near future, if that's any consolation.
