### ISSUE TITLE
how to output unescaped UTF-16 encoded string

### ISSUE THREAD

**Issue by missdeer** [boostorg/json#672]
I'm using Boost 1.78.0, want to get serialize result like 
```js
{
    "key": "\u1234"
}
```
Is it possible with current release?

**Comment by grisumbras** [comment]
Your example doesn't explain much. You want to serialize json as a UTF-16 document? Or you have a string with text in UTF-16 and you want to re-encode it as UTF-8?

**Comment by missdeer** [comment]
```cpp
boost::json::object rootObj;
rootObj["key"]="一些用UTF-8编码的CJK字符"; // some CJK characters encoded as UTF-8

std::string json = boost::json::serialize(rootObj);
```
I want to get `json` like something in my initial post.

**Comment by grisumbras** [comment]
So, you want to output in UTF-16? We don't support serialization as UTF-16 (or UTF-32) at this point.

**Comment by missdeer** [comment]
Got it. Thanks.
