### ISSUE TITLE
Does it support std::optional or boost::optional out of the box ?

### ISSUE THREAD

**Issue by vricosti** [boostorg/json#677]
Hello,

Does it support simple json conversion from `std::optional<std::string>` for instance ? When I test I get some errors.
Thanks

**Comment by grisumbras** [comment]
Not yet, but it will be most likely added in the future.

**Comment by vinniefalco** [comment]
What would "supporting optional" look like? Can you please give example code (using types from Boost.JSON)?

**Comment by toonetown** [comment]
As I am looking into `boost::json` more, I think it might be achievable outside the library by treating `null` values as an optional with no value.  Perhaps supporting it inside the `boost::json` library is not necessary nor desirable.

**Comment by pdimov** [comment]
> What would "supporting optional" look like?

Default implementations of `value_from` and `value_to` for `std::optional<T>`.

**Comment by grisumbras** [comment]
To be honest, the hardest part of implementing this feature is determining a good trait for what is and isn't an optional. I.e. is checking that the type is `std::optional<T>` good enough? I suspect people would expect `boost::optional` to be supported too.

**Comment by madmongo1** [comment]
Optionals have the member functions .has_value() and .get()
That’s probably enough?

**Comment by grisumbras** [comment]
Yeah, could work

**Comment by pdimov** [comment]
`boost::optional` can be supported on the `boost::optional` side. There's no need for JSON to know about all the optionals.

**Comment by NexusHero** [comment]
Is there a timeline for this feature?

**Comment by grisumbras** [comment]
Most likely before the next Boost release (December)
