### ISSUE TITLE
Inserting values at pointers

### ISSUE THREAD

**Issue by doganulus** [boostorg/json#700]
Currently trying out the new JSON pointer implementation and I think this would be very useful in many cases.

One thing I have needed is inserting or assigning arbitrary JSON values at locations specified by JSON pointers. Is it currently possible? How can I achieve it in the current state?

**Comment by sehe** [comment]
Please describe what you consider "JSON pointers". Do you mean some XPath like query syntax? Specifically, what syntax? Is there a standard for it?

**Comment by pdimov** [comment]
Not a duplicate. That issue is about finding an element by its path, and this one is about inserting an element at a specified path.

**Comment by grisumbras** [comment]
Just to be sure, this is about creating intermediary objects, right? Do you also have any suggestions on how to deal with non-existant elements of arrays?

**Comment by doganulus** [comment]
Yes, non-existent objects are to be created at the insertion. For example,

```
value jv1 {{"a": {{"b", 1}}}};
value jv2 {{"c": {{"d", 2}}}};

jv1.insert_or_assign("/x", jv2);
jv1.insert_or_assign("/a/b", jv2);

assert(jv1.at_pointer"/x/c/d" == 2)     // new value inserted at previously non-existent path /x
assert(jv1.at_pointer("/a/b/c/d") == 2) // new value assigned at the existing path /a/b
```

For non-existent array elements, I think `std::vector` assignment behavior might be preferable. Assign the value if the index is in range or else return an out-of-range/not-found error. Inserting to the back of an array can be specified using `-` character according to [RFC 6901](https://datatracker.ietf.org/doc/html/rfc6901#section-4). A helper function to get the size of a `json::array` at a given pointer path may be needed as well.

**Comment by doganulus** [comment]
Further investigations with the current API:

For objects:
```
value jv = {{"abc", {{"xyz", {12, 13, 15}}}}};

jv.at_pointer("/abc/xyz") = {"123", "1231"}; // works as desired
jv.at_pointer("/abc/klm") = {"123", "1231"}; // does not work but desired
```

For arrays:
```
value jv = {{"abc", {{"xyz", {12, 13, 15}}}}};

jv.at_pointer("/abc/xyz/0") = {"123", "1231"}; // works as desired
jv.at_pointer("/abc/xyz/3") = {"123", "1231"}; // does not work as desired
jv.at_pointer("/abc/xyz/-") = {"123", "1231"}; // does not work but desired
```

**Comment by pdimov** [comment]
We're having differences of opinion on what `jv.insert_at_pointer("/a/2", 5)` needs to create, an array or an object. @grisumbras thinks it should create an object and set its `"2"` key to 5. I find this consistent but kind of not really doing what one would want in the majority of cases. It seems to me that it should create an array and set its third element to 5 (leaving the first two `null`).

**Comment by pdimov** [comment]
There's no use case for (1) if you don't have (2)+(3).

**Comment by pdimov** [comment]
(1) is useful if one has (3) and wants to maintain order independence as in
```
value jv = array();
jv.assign_at_pointer("/1/y", 5);
jv.assign_at_pointer("/0/x", 3);
```
giving the same result as
```
jv.assign_at_pointer("/0/x", 3);
jv.assign_at_pointer("/1/y", 5);
```
because there's an implicit `null` created by the first line.

On second thought, though, I no longer favor (3) because it makes denial of service attacks trivial (`"/123456789"`). So I agree that numeric indices should be constrained to [0, size()] (with `-` being the same as `size()`.)

**Comment by doganulus** [comment]
RapidJSON implements the behavior (3). The program below is problematic as @pdimov points.

```
#include <iostream>

#include "rapidjson/document.h"
#include "rapidjson/pointer.h"

using namespace rapidjson;

int main()
{
  const char* json = R"({"my_obj": { "my_arr": [10,11,12]}})";
  Document d;
  d.Parse(json);

  Document v;
  v.Parse("20");
  SetValueByPointer(d, "/my_obj/my_arr/999999999", v);

  return 0;
}
```

**Comment by grisumbras** [comment]
Interesting. So RapidJSON says yes to 1, 2, and 3. And even converts other kinds of values to arrays and objects, not just nulls. Maybe we need 2 kinds of functions: one conservative and one "helpful".

**Comment by grisumbras** [comment]
@doganulus @pdimov can you check out #713 to see if you agree with the choices made in that implementation.
The choices are:

1. Nulls are replaced when creating intermediate elements.
2. When creating intermediate elements segments are always treated as object keys, (in other words, only objects are created as intermediates).
3. Arrays are extended by 1 element at most.

**Comment by doganulus** [comment]
One question: Can we set values at intermediate keys as follows?

```
jv = value();
result = &jv.set_at_pointer("/a/b/c", "m"); //
result = &jv.set_at_pointer("/a/b", "n");
```

Or the option `replace_any_scalar` just implies that we can only replace the leaf values?

**Comment by grisumbras** [comment]
```c++
value jv = 1;
jv.set_at_pointer("/a/b/c", "m"); // exception
jv.set_at_pointer("/a/b/c", "m", {.replace_any_scalar}); // success
```

**Comment by grisumbras** [comment]
```c++
value jv = 1;
jv.set_at_pointer("/a/b/c", "m"); // exception
jv.set_at_pointer("/a/b/c", "m", {.replace_any_scalar}); // success
```
