### ISSUE TITLE
Remove unnecessary header

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/json#714]
The header `boost/exception/diagnostic_information.hpp` is unnecessary. It increases the library weight in the boost dependency report.

https://github.com/boostorg/json/blob/4797be3eac137729679403b89bd4f8580797737b/include/boost/json/detail/except.hpp#L15

### Version of Boost

develop

### Steps necessary to reproduce the problem

Use the library as usual. Not really a bug.

### All relevant compiler information

Any compiler. Not really a bug.

**Comment by vinniefalco** [comment]
Why is this an issue instead of a pull request?

**Comment by alandefreitas** [comment]
> Why is this an issue instead of a pull request?

:)

Because I'm looking at boost.url right now but didn't want to forget about this.

**Comment by vinniefalco** [comment]
Oh.. and its in JSON... derp

**Comment by alandefreitas** [comment]
Yes. I already fixed this in boost.url.
