### ISSUE TITLE
Unable to include boost in .h file and then use library in .cpp implementation of .h file

### ISSUE THREAD

**Issue by Abuzik** [boostorg/json#729]
boost 1.79.0
If we've for example Class.h and Class.cpp and #include "boost/json.hpp" in Class.h we'll get an error with duplicating symbol. Other boost libraries is ok with that configuration.

**Comment by grisumbras** [comment]
There's not enough information in your description of the issue. What's the OS? What's the compiler? How do you link to the library? Did you follow the documentation on how to use the library?

**Comment by Abuzik** [comment]
> There's not enough information in your description of the issue. What's the OS? What's the compiler? How do you link to the library? Did you follow the documentation on how to use the library?

Mac OS Monterey 12.0.1. 
Compiler: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

**Comment by vinniefalco** [comment]
Pay attention to the section in **bold**:
> To use as header-only; that is, to eliminate the requirement to link a program to a static or dynamic Boost.JSON library, simply place the following line in **exactly one new or existing source file** in your project.

https://www.boost.org/doc/libs/1_79_0/libs/json/doc/html/json/overview.html#json.overview.requirements.header_only

You are including src.hpp multiple times.

**Comment by Abuzik** [comment]
> Pay attention to the section in **bold**:
> 
> > To use as header-only; that is, to eliminate the requirement to link a program to a static or dynamic Boost.JSON library, simply place the following line in **exactly one new or existing source file** in your project.
> 
> https://www.boost.org/doc/libs/1_79_0/libs/json/doc/html/json/overview.html#json.overview.requirements.header_only
> 
> You are including src.hpp multiple times.

Oh, I haven't seen that, sorry then.
