### ISSUE TITLE
doc glitch

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#730]
This needs to be checked in 1.80. `detail::find_in_object` should not be visible:

https://www.boost.org/doc/libs/1_79_0/libs/json/doc/html/json/ref/boost__json__object.html

![image](https://user-images.githubusercontent.com/1503976/180567870-6059fc6f-e3f2-4ad5-9881-4a6ab3c2b625.png)

**Comment by grisumbras** [comment]
Fixed at some point in the past.
