### ISSUE TITLE
Boost 1.80.0 JSON error

### ISSUE THREAD

**Issue by g2px1** [boostorg/json#751]
/usr/local/include/boost/json/impl/object.ipp:34: std::pair<boost::json::key_value_pair*, long unsigned int> boost::json::detail::find_in_object(const boost::json::object&, CharRange) [with CharRange = boost::core::basic_string_view<char>]: Assertion `obj.t_->capacity > 0' failed.

Unfortunately, I can't provide steps to represent error due I've found this error in logs but I hope it would be helpful. Also can give link to project where this error occurred but project has a complex structure

**Comment by vinniefalco** [comment]
Does `object::find` work when the container is default constructed?

**Comment by Abuzik** [comment]
> Does `object::find` work when the container is default constructed?

Manually I'm not using this function, maybe it contains in boost::json's functions. I can send you link to repository(and files which are using boost) with my code by email

**Comment by vinniefalco** [comment]
This is more a question for @grisumbras , as it is easily tested.

**Comment by grisumbras** [comment]
Yeah, extra info is necessary to investigate this issue.

**Comment by grisumbras** [comment]
Since I can't do anything with only this information, I'm closing the issue.
