### ISSUE TITLE
Insert object into an existing object as a key-value-pair

### ISSUE THREAD

**Issue by Tabascl** [boostorg/json#754]
Boost Version 1.80
I have a class hierarchy that looks like this: class A is composed of classes B and C.
B and C each have a function that returns boost::json::object, which looks like this in case of B: `{"B": "someValue"}`

A is supposed to compose each of these objects into a structure like this:
```
{
  "A": {
    "B": "someValue",
    "C": "someOtherValue"
  }
}
```

The problem I'm facing is, that the resulting object always looks like this:
```
{
  "A": [
    { "B": "someValue" },
    { "C": "someOtherValue" }
  ]
}
```
As you can see, the objects from the subclasses are not added as key-value pairs, but as objects, each containing a single pair, into an array.

Here's a snippet to reproduce the issue:
```
#include <iostream>
#include <boost/json.hpp>

using namespace boost::json;

object makeObject(std::string key, int value)
{
    object obj;
    obj[key] = value;
    return obj;
}

int main() {
    object obj;
    obj["main"] = {makeObject("test1", 123), makeObject("test2", 456)};

    std::cout << obj << std::endl;
    return 0;
}
```

According to the Quick Look documentation, I would have expected this to not create an array with single-value objects in it.
What am I doing wrong here?

**Comment by grisumbras** [comment]
The correct incantation in this case should probably be
```c++
{ {"test1", 123}
, {"test2", 456}
}
```

**Comment by Tabascl** [comment]
Maybe I should have been more clear here, I sadly can't do the incantation like you said. The makeObject function is here to enable a very simple example that shows the problem.
Here's a more complete example, that hopefully outlines my problem a bit better:
```
#include <boost/json.hpp>
#include <iostream>

using namespace boost::json;

class B
{
public:
    object makeProp()
    {
        object obj;
        obj["B"] = {{"property1", 1}};
        return obj;
    }
};

class C
{
public:
    object makeProp()
    {
        object obj;
        obj["C"] = {{"property1", 1}, {"property2", {1, 2, 3}}};
        return obj;
    }
};

class A
{
public:
    object makeProp()
    {
        B b;
        C c;

        object obj;
        obj["A"] = {b.makeProp(), c.makeProp()};
        return obj;
    }
};

int main()
{
    A a;
    std::cout << a.makeProp() << std::endl;

    return 0;
}
```
Hopefully the purpose of the makeObject-function in the original example is clearer now. I somehow need to insert objects created elsewhere directly into another one.

**Comment by vinniefalco** [comment]
So what are you expecting here, a 2-element array?
```
 obj["A"] = { b.makeObject(), c.makeObject() };
```

**Comment by vinniefalco** [comment]
It sounds like perhaps you are asking to merge the key/value pairs in one object, into another object? so you want `obj` to contain three elements, with keys "A", "B", and "C"?  Does this issue describe your problem?
https://github.com/nlohmann/json/issues/1807

**Comment by vinniefalco** [comment]
Is this what you are looking to do?
https://github.com/vinniefalco/json/blob/f07024e2dd7019d6f504602a45a552f9eaabbfa8/example/merge.cpp#L125

**Comment by Tabascl** [comment]
> Is this what you are looking to do? https://github.com/vinniefalco/json/blob/f07024e2dd7019d6f504602a45a552f9eaabbfa8/example/merge.cpp#L125

This is exactly what I was looking for. Thanks a lot!

**Comment by grisumbras** [comment]
I think, this should be equivalent to what @vinniefalco suggested
```c++
object&
merge_objects(
    object& dest,
    object src)
{
    dest.insert(
        std::make_move_iterator(src.begin()),
        std::make_move_iterator(src.end()));
    return dest;
}
...
object obj;
obj["A"] = object();
merge_objects(obj, make_B());
merge_objects(obj, make_C());
```
