### ISSUE TITLE
Typo in doco for serializer

### ISSUE THREAD

**Issue by matty0ung** [boostorg/json#767]
At https://github.com/boostorg/json/blob/2d0bef633d47418461710639fda58f6db68f6def/doc/qbk/02_09_serializing.qbk#L56-L57 "incrementally" is repeated.

**Comment by vinniefalco** [comment]
Yeah that doesn't sound great, thanks :)

**Comment by grisumbras** [comment]
Fixed in 59abf5dbf061300d9b5c23f3b3910d309a990593
