### ISSUE TITLE
Boost.JSON (from Boost 1.81.0 beta RC 1) fails to compile with X11 headers

### ISSUE THREAD

**Issue by mclow** [boostorg/json#803]
Captured from the boost mailing list (11/11/22, in a message about the Boost 1.81.0 beta 1 release candidate:

I am getting compile errors when using the beta.  It seems that Boost.Json uses the identifier Opposite as a template argument, but X.h (from X11) contains the following line:

 #define Opposite                4

This is a regression from Boost version 1.80.0.

**Comment by grisumbras** [comment]
Yeah, I've seen itvon ML. Will fix soon.
