### ISSUE TITLE
Assertion failure in basic_parser under mingw-gcc and clang-win 32 bit

### ISSUE THREAD

**Issue by pdimov** [boostorg/json#828]
I'm getting [CI failures](https://github.com/pdimov/mustache/actions/runs/3791897844/jobs/6447659398) with the following in the log:
```
====== BEGIN OUTPUT ======
Assertion failed!

Program: D:\a\mustache\boost-root\bin.v2\libs\mustache\test\spec_interpolation.test\gcc-8\debug\cxxstd-2a-iso\threading-multi\visibility-hidden\spec_interpolation.exe
File: ./boost/json/basic_parser_impl.hpp, Line 1014

Expression: *cs == '\x22'
 
EXIT STATUS: 3 
====== END OUTPUT ======
```
The minimal program reproducing the failure under clang-win 32 bit is:
```
#include <boost/json.hpp>
#include <boost/core/verbose_terminate_handler.hpp>
#include <fstream>

int main()
{
    std::set_terminate( boost::core::verbose_terminate_handler );
    std::ifstream is( "interpolation.json" );
    boost::json::parse( is );
}
```
where `interpolation.json` is taken from here: https://github.com/mustache/spec/blob/5d3b58ea35ae309c40d7a8111bfedc4c5bcd43a6/specs/interpolation.json

**Comment by grisumbras** [comment]
```
Program: D:\a\mustache\boost-root\bin.v2\libs\mustache\test\spec_interpolation.test\gcc-8\debug\cxxstd-2a-iso\threading-multi\visibility-hidden\spec_interpolation.exe
```
Doesn't look like clang-win, looks more like mingw

**Comment by pdimov** [comment]
clang-win asserts in the same place, but that's not visible in the CI log because it times out due to the assertion popup.

**Comment by grisumbras** [comment]
My investigation discovered that this is the result of buffer, from which the parser reads, being put immediately before the parser object, and thus past-the-end address of the buffer becoming `this` address of the parser. So, #814 should fix the issue.

**Comment by grisumbras** [comment]
Should be fixed on develop. I checked locally, and the file in the description parses without errors.
