### ISSUE TITLE
Confusing terminology in the docs

### ISSUE THREAD

**Issue by JankoDedic** [boostorg/json#841]
I've noticed that in some places like [here](https://www.boost.org/doc/libs/1_78_0/libs/json/doc/html/json/input_output.html#json.input_output.parsing), the term "a JSON" is used, for example:

>In the following example **a JSON** is parsed from standard input a line at a time.

Does this mean "a JSON value" or "a JSON text"? The latter is used in some places in the docs. Is this something different? I don't see the term "a JSON" defined in the [RFC](https://www.rfc-editor.org/rfc/rfc8259).

May I request clarification?
Thanks

**Comment by cdesouza-chromium** [comment]
Yeah, the ecma standard also seems to agree with the description of this issue.

https://262.ecma-international.org/13.0/#sec-json.parse

> 25.5.1 JSON.parse ( text [ , reviver ] )
The parse function parses a JSON text (a JSON-formatted String) and produces an ECMAScript language value. The JSON format represents literals, arrays, and objects with a syntax similar to the syntax for ECMAScript literals, Array Initializers, and Object Initializers. After parsing, JSON objects are realized as ECMAScript objects. JSON arrays are realized as ECMAScript Array instances. JSON strings, numbers, booleans, and null are realized as ECMAScript Strings, Numbers, Booleans, and null.

Seems weird that most of the documentation in this lib has chosen this unusual wording, that goes against any other web standard.

**Comment by vinniefalco** [comment]
Current wording:

> Parsing is the process where a serialized JSON is validated and decomposed into elements

Should we say "JSON text?" What new wording are you proposing?

**Comment by JankoDedic** [comment]
Yeah, I think "JSON text" would be right.

**Comment by vinniefalco** [comment]
Do you want to submit a pull request to fix it all?

**Comment by cdesouza-chromium** [comment]
I don't think I would be able to, unfortunately.

**Comment by vinniefalco** [comment]
Who is using this library?

**Comment by cdesouza-chromium** [comment]
I came across that wording as I was studying the library to use it.

**Comment by cdesouza-chromium** [comment]
Sorry but this is not fixed:

> The library expects input text to be encoded using UTF-8, which is a requirement put on all JSON exchanged

It is not only NOT fixed, but also additional confusing terminology has been added.

**Comment by cdesouza-chromium** [comment]
Thanks for fixing this.
