### ISSUE TITLE
value_to object with stateful allocator such as std::pmr::string

### ISSUE THREAD

**Issue by star-e** [boostorg/json#854]
How can we construct a `std::pmr::string` using `value_to`, with user-provided `std::pmr::memory_resource*`?
Here, the object and the json value are using different `memory_resource` sources.

The customization function's signature is `T tag_invoke( const value_to_tag< T >&, const value& )`, which does not take any `Allocator` as parameter. So there is no way to provide the allocator.

It seems we can only construct `std::pmr::string` from `std::pmr::get_default_resource()`?

**Comment by grisumbras** [comment]
Yes, it's not currently possible, but the feature that will allow it is being worked on.

**Comment by star-e** [comment]
That's great, thanks!

**Comment by vinniefalco** [comment]
@star-e are you using the global memory resource or are you using a custom resource (like a monotonic resource)? Which memory resource are you actually using?

**Comment by star-e** [comment]
I am using a custom resource, such as `std::pmr::synchronized_pool_resource`, not global memory resource.
I use memory resources from `std::pmr` (monotonic, sync pool, unsync pool), and some custom resource like `counting_memory_resource`.
They are all derived from `std::pmr::memory_resource`.

**Comment by grisumbras** [comment]
Please check out #819.
Docs for contextual conversions: https://819.jsondocs.prtest.cppalliance.org/libs/json/doc/html/json/conversion/contextual_conversions.html
Example of passing allocator to a conversion: https://819.jsondocs.prtest.cppalliance.org/libs/json/doc/html/json/examples.html#json.examples.allocator_aware_conversion
