### ISSUE TITLE
stream_parser assertion failure when input is split just before colon

### ISSUE THREAD

**Issue by mjerabek** [boostorg/json#879]
When the input for `stream_parser` is split in a particular way, an assertion is triggered inside of the library. On other occasions, I get "syntax error", although the JSON is perfectly valid. Note that the included reproducer is reduced to triggering the assert (and I hope the syntax error is just a different manifestation of the same bug).

**Note**: this happens only on gcc and only in specific optimization levels - `-O0`/`-O1` trigger the bug, while with `-O2`/`-O3` the assertion is not triggered (which is IMHO rather weird).

Further oddities are described in the reproducer.

### Version of Boost

1.81.0

### Steps necessary to reproduce the problem

Fortunately it's reproducible on compiler explorer: https://godbolt.org/z/Ea3a5zvvP

**Comment by grisumbras** [comment]
This is almost certainly a duplicate of #828 . Can you test if the problem goes away with Boost 1.82?

**Comment by mjerabek** [comment]
Thank you! I didn't know 1.82 was already out, plus I forgot to check already closed issues :facepalm: .

Works with both 1.82 and 1.81 with the patch backported.
