### ISSUE TITLE
remove type aliases

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/json#881]
we should get rid of our aliases for error_code, result, et. al. and just use them directly from system.

**Comment by grisumbras** [comment]
Well, they make code smaller a little bit. Do they create a problem?

**Comment by vinniefalco** [comment]
It just can be a little confusing, documentation-wise. And when you are using multiple libraries that are in the habit of creating aliases for error_code, result, and the rest, now you have a lot of aliases...

**Comment by grisumbras** [comment]
There's an insane amount of projects on GH that use `json::error_code`. I feel like removing the alises will cause unnecessary chaos.

**Comment by vinniefalco** [comment]
Interesting, did not know that

**Comment by grisumbras** [comment]
For reference: https://github.com/boostorg/url/issues/743.

The appropriate action is to deprecate aliases first, then remove after a few releases.
