### ISSUE TITLE
Exception in custom tag_invoke(value_to_tag)

### ISSUE THREAD

**Issue by RoyBellingan** [boostorg/json#903]
### Version of Boost
1_82

For example here (but this code pattern is common in other places)

https://github.com/boostorg/json/blob/be759c5051b828f77b59d5c67b9b53d7330e627e/include/boost/json/detail/value_to.hpp#LL652C44-L652C54

In case a custom tag_invoke throw the information on why and where is either lost or severely reduced (just the error.code() is passed in the chain) like here https://github.com/boostorg/json/blob/be759c5051b828f77b59d5c67b9b53d7330e627e/include/boost/json/detail/value_to.hpp#LL652C44-L652C54

I think it can make sense to allow (like is happening for std::bad_alloc ) to leave certain exception to be re thrown.

**Comment by grisumbras** [comment]
Throwing overloads of conversion functions should allow exceptions to pass through. Do you have a specific example when that doesn't happen?

**Comment by RoyBellingan** [comment]
Well the value_to_impl linked above has
    catch( ... )
    {
        error_code ec;
        BOOST_JSON_FAIL(ec, error::exception);
        return {boost::system::in_place_error, ec};
    }
    That will intercept all of them.
Give me 5 min I will write a godbolt example.

**Comment by RoyBellingan** [comment]
For example here https://godbolt.org/z/767674j5c
The result I got is 

terminate called after throwing an instance of 'boost::detail::with_throw_location<boost::system::system_error>'
  what():  got exception [boost.json:15 at /opt/compiler-explorer/libs/boost_1_82_0/boost/json/detail/value_to.hpp:671:9 in function 'typename std::enable_if<(! typename boost::mp11::detail::mp_valid_impl<boost::json::detail::has_nonthrowing_user_conversion_to_impl, T>::type::value), boost::system::result<T> >::type boost::json::detail::value_to_impl(boost::json::try_value_to_tag<T>, const boost::json::value&, user_conversion_tag)']

**Comment by RoyBellingan** [comment]
Instead if I do NOT use the BOOST_DESCRIBE_STRUCT method the exception is correctly passed, a few moment I assemble an example

**Comment by grisumbras** [comment]
You are right, I somehow missed that. I will look into ways to fix that.

**Comment by grisumbras** [comment]
@RoyBellingan can you check if #913 fixes your problem?
