### ISSUE TITLE
Operator[] / emplace / insert_or_assign on existing key may cause iter invalidation

### ISSUE THREAD

**Issue by mokeevdmitrii** [boostorg/json#906]
### Version of Boost

1.82

### Steps necessary to reproduce the problem

https://godbolt.org/z/MeKzYbqsv

Crashes, because `operator []` called with existing key as an argument causes reallocation and iterator invalidation ignoring the fact the key hasn't really been inserted. According to docs, iterators are not affected if the key isn't inserted.

### All relevant compiler information

LLVM Clang 16.0.0
Originally found on MacOS Ventura 13.2.1

#### Notes 
Relevant documentation for operator[] ([reference](https://www.boost.org/doc/libs/master/libs/json/doc/html/json/ref/boost__json__object/operator_lb__rb_.html)) declares that iterator invalidation happens only on successful value insertion. However, [as it can be found in source code](https://github.com/boostorg/json/blob/ee01580cfde818e31d8ea41c2e4056bcff9e3018/include/boost/json/impl/object.ipp#L598) for boost 1.82 (older versions too, probably), operator[] works via calling `emplace(key, nullptr)`. 

The real "problem" lies in the `boost::json::object::emplace` function. It is said in the docs it works the same way as `[]` - invalidation only upon insertion. Unfortunately, it's not stated that `emplace` always ([ref to boost 1.82 source](https://github.com/boostorg/json/blob/ee01580cfde818e31d8ea41c2e4056bcff9e3018/include/boost/json/impl/object.hpp#L410)) reserves memory for at least `size() + 1` elements before checking should the element be inserted or not - so iterators **could** be invalidated (if you are unlucky) even on unsuccessful insertion.

#### Suggested change

Haven't prepared the MR though, but I suppose it would be enough to move lines with memory reservation in `boost::json::object::emplace` and `boost::json::object::insert_or_assign` below checking for existing with (maybe) some extra checks (as `detail::find_in_object` asserts for non-zero capacity, for example).

**Comment by grisumbras** [comment]
This is technically a documentation issue, but I'm sure we should be able to make these functions provide the basic guarantee.

**Comment by vinniefalco** [comment]
I tried my best to offer the strong guarantee everywhere, it would be disappointing to not achieve that

**Comment by mokeevdmitrii** [comment]
actually found this to be a duplicate of https://github.com/boostorg/json/issues/763, so you may close this one :)
