### ISSUE TITLE
target_compile_features specified unknown feature

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/json#910]
### Version of Boost

develop

### Steps necessary to reproduce the problem

We just started getting this error in CI:

```
CMake Error at libs/json/CMakeLists.txt:57 (target_compile_features):
  target_compile_features specified unknown feature "_SCL_SECURE_NO_WARNINGS"
  for target "boost_json".
```

The complete output: https://github.com/boostorg/url/actions/runs/5336814814

### All relevant compiler information

The error happens in MSVC 14.34, MSVC 14.29, MinGW, and clang-cl.

**Comment by grisumbras** [comment]
Oops, that was a bad copypaste on my part.

**Comment by grisumbras** [comment]
Can you check if #911 fixes this?

**Comment by alandefreitas** [comment]
I had a look at #911, if `target_compile_definitions(${target} PRIVATE _SCL_SECURE_NO_WARNINGS)` doesn't fix the original problem, it sure won't cause other people this problem (#910). The definition is even private.
