### ISSUE TITLE
Minor nit: typo in "About"

### ISSUE THREAD

**Issue by jfolker** [boostorg/json#931]
"A C++11 **or** library for parsing and serializing JSON to and from a DOM container in memory."

**Comment by grisumbras** [comment]
Can you give a link to the page that has that? I can't find anything like it in our docs.

**Comment by jfolker** [comment]
The "About" blurb on github:

https://github.com/boostorg/json

**Comment by grisumbras** [comment]
Oh, thanks! Fixed.
