### ISSUE TITLE
SEGFAULT when accessing existing and filled fields of a boost::json::object, strange behavior when logging

### ISSUE THREAD

**Issue by StormLord07** [boostorg/json#944]
### Version of Boost

Boost 1.83.0

### Steps necessary to reproduce the problem

Ok the  problems seems simple

If you have a function, like this

```
void callback(boost::json::object &obj) {
    auto value = boost::json::value_to<std::string>(obj["key"]); // or int64_t doesn't matter
    #operation with value
}
```

it throws an error like

```
terminate called after throwing an instance of 'boost::detail::with_throw_location<boost::system::system_error>'                                                                                                                               what():  not a number [boost.json:24 at /usr/local/include/boost/json/value.hpp:2374:9 in function 'typename std::enable_if<(std::is_arithmetic<_Tp>::value && (! std::is_same<T, bool>::value)), T>::type boost::json::value::to_number(boost::json::error_code&) const']
```

or not a string error, which I can't find or reproduce 90% of the time

however if i try to log the obj beforehand

```
void callback(boost::json::object &obj) {
    std::string jsonString = boost::json::serialize(obj);
    BOOST_LOG_TRIVIAL(info) << jsonString;
    auto value = boost::json::value_to<std::string>(obj["key"]); // or int64_t doesn't matter
    /*operation with value*/
}
```

It doesn't crash at all, I've been running the app with the same data for a day, and it doesn't crash, before it crashed a few minutes in, I can reproduce the error outside my app which I unfortunately can't share. Nothing but added logging was added, When talking with my friend, he had the same error and adding logging also "fixed" the problem. I'm dumb folded, because I don't understand how it happens, nor how to reproduce it with at least some consistency. 

P.S. Might help that I call function by a pointer: In different files I have different classes, in `class1` I call function from `class2` that sets it's `call` variable to a pointer of a function and then if conditions are met the function is called like this `call(obj)`, `call` from `class2` in this case points to a `callback` function in `class1`.
`class2` knows about `class1`, not vice versa.

P.P.S. I know that fields were filled because before the function call I had it logged in another place. and GDB also showed it being filled.

### All relevant compiler information

make, g++ 14, cmake 3.26.

**Comment by grisumbras** [comment]
I need more info to reproduce the problem. So far looks like in one case you have the key in the object, and in another one you don't. But as I understand, this isn't the case.

**Comment by grisumbras** [comment]
This still isn't enough information to understand why you're having this problem. I need something I try locally. Without that I can only speculate.

So, here's the speculation. You use `ThreadSafe::vector`, which implies using threads. If a key is missing before logging and is present after the logging, then I suspect another thread adds that key, while logging is performed. This can happen if you're not synchronising accesses to your data properly.

Can you rewrite your example to not use threads to see if that is indeed the case?

**Comment by StormLord07** [comment]
I'll try to reproduce  this in other app when I'll have free time, Maybe adding value in threads are the case, but its still weird, because the above code executed only after threads have exited.

**Comment by StormLord07** [comment]
I have tried to reproduce that in both multithreaded environment and in the one thread, just a very simplified version of the functions. 

```
#include <iostream>
#include <thread>
#include <chrono>
#include <atomic>
#include <boost/json.hpp>
#include <boost/log/trivial.hpp>
#include "threadSafeVector.h"

class Bot {
public:
    using CallbackFunction = std::function<void(boost::json::object &)>;

    Bot(const std::string &api, int64_t id)
        : api_key(api), tr_id(id) {
    }

    void setCallbackFunction(CallbackFunction function_ptr) {
        this->call = function_ptr;
    }

    void processTransactions(boost::json::object transactions) {
        auto now = std::chrono::system_clock::now();
        std::time_t time_now = std::chrono::system_clock::to_time_t(now);
        std::tm *now_tm = std::localtime(&time_now);

        if (now_tm->tm_sec > 2) {
            call(transactions);
            // For demonstration, log transaction instead of sending to Telegram
            BOOST_LOG_TRIVIAL(info) << "Processed transaction with ID: " << boost::json::value_to<std::string>(transactions["amount"]);
        }
    }

private:
    std::string api_key;
    int64_t tr_id;
    CallbackFunction call;
};

ThreadSafe::vector<boost::json::object> callbackTransactions;

void addTransactions(const std::string &jsonData) {
    boost::json::value val = boost::json::parse(jsonData);
    boost::json::object obj = val.as_object();

    if (obj["result"].as_int64() == 1) {
        for (auto &payout : obj["payouts"].as_array()) {
            callbackTransactions.push_back(payout.as_object());
        }
    }
}

int main() {
    Bot bot("api_key_here", 1234);

    bot.setCallbackFunction([](boost::json::object &obj) {
        // ... Do something with transaction (this is where you'd normally send to Telegram)
        });

    std::string jsonData = R"({
        "result": 1,
        "payouts": [
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"},
            {"id": 101282150, "amount": "3000.00"}
        ]
    })";

    while (true) {
        auto now = std::chrono::system_clock::now();
        std::time_t time_now = std::chrono::system_clock::to_time_t(now);
        std::tm *now_tm = std::localtime(&time_now);

        if (now_tm->tm_sec <= 2) {
            // Add transactions in the first two seconds
            addTransactions(jsonData);
            std::this_thread::sleep_for(std::chrono::milliseconds(50));
        }
        else {
            for (auto transaction : callbackTransactions) {
                bot.processTransactions(transaction);

            }
            callbackTransactions.clear();
        }
    }

    return 0;
}
```

Still couldn't reproduce it, this had the error after running for an hour, and then nothing, the error is more frequent in a real system, but unfortunately hardly reproducible in a test environment.

I'll show this thread to my friend who had the same issue, maybe he'll help a little more

**Comment by grisumbras** [comment]
> P.S. Why serializing "fixes" issue if the problem is multithreading the problem is in a called function, that has a copy of the value at the moment of calling.

```C++
void name(boost::json::object &obj) {
```
Where's the copy?

**Comment by StormLord07** [comment]
Ok, my mistake, I overlooked that, in other commit i was creating a copy of transaction, that i was passing into call nothing was changed, moreover it's still strange, I use "custom" thread safe vector that mutex locks container untill finished [this](https://github.com/Unit-chain/Unit/blob/7278934590505ae3a468081a3c998132ef9c68d4/unit/libdevcore/datastructures/containers/vector.h#L13)

**Comment by grisumbras** [comment]
Again, it's hard to investigate without seeing the actual code that misbehaves. I can speculate, that since your vector synchronizes on begin and end, but does not synchronize on iterator increments and iterator dereference, the objects accessed can be left in unmodified state depending on chance. It's better to have a sort of queue API with enqueue/dequeue. And after dequeueing you don't access the shared data between threads.

**Comment by StormLord07** [comment]
Ok, after a lot of testing. The problem was indeed in thread syncronisation, somehow, sometimes, telegram interface decided to work superfast and make everything in milliseconds insted of a second which my system was mostly designed for, and a header for a thread safe vector isn't that thread safe as wanted.

Conclusion: always check what code you use.
