### ISSUE TITLE
boost::json::value_to on std::bitset?

### ISSUE THREAD

**Issue by infn-ke** [boostorg/json#966]
Does boost json support std::bitset? On boost json 1.82 I cannot use `boost::json::value_to` on a `std::bitset`,  does this require a custom `tag_invoke`?

**Comment by grisumbras** [comment]
We don't support it at the moment. But we probably should.

**Comment by infn-ke** [comment]
Ok, thanks for confirming. I added handling of them using ADL and that works for me.

**Comment by pdimov** [comment]
What is your chosen JSON representation of a std::bitset?

**Comment by grisumbras** [comment]
Maybe I should reopen the issue snd rename it to "add conversion implementation for std::bitset"?

**Comment by infn-ke** [comment]
> Maybe I should reopen the issue and rename it to "add conversion implementation for std::bitset"?

Ok for me if you want.  I guess I would have to remove my `tag_invoke` implementation once boost natively handles bitsets?
