### ISSUE TITLE
If an unsigned integer is serialized, deserializing back to the unsigned integer fails

### ISSUE THREAD

**Issue by DUOLabs333** [boostorg/json#973]
When reporting a bug please include the following:

### Version of Boost
1.84
### Steps necessary to reproduce the problem
1. Serialize `uint8_t test=8;`
2. Parse it back into a value `value test_value=serialize(value_from(test));`
3. Try to get the number with `value_to<uint8_t>(test_value)`
4. See the exception `Not exact`.

**Comment by grisumbras** [comment]
Step 2 doesn't compile for me at all. Can you please provide an actual minimal, complete and verifiable example (MCVE)?

Although, let's consider this one:
```c++
#include <boost/json.hpp>
#include <cassert>

int main()
{
        uint8_t test = 8;
        value test_value = value( serialize(value_from(test)) ); // (1); notice explicit constructor
        auto test2 = value_to<uint8_t>(test_value); // (2)
        assert( test == test2 );
        return 0;
}
```

Here (1) converts the integer `test` to `json::value`, then serializes that into `std::string`, then assigns *that string* to a new `json::value`. This is equivalent to doing `value test_value = "8";` 

(2) tries to convert _that JSON string_ into a number, and predictably fails. But the error is "not a number".

Then, I guess, this is still not something that you are doing. So, please provide an MCVE.

**Comment by DUOLabs333** [comment]
This replicates it:
```
#include <boost/json/src.hpp>
using namespace boost::json;
#include <cassert>

int main()
{		
		object test;
        test["value"]=160;
        object test_new = parse( serialize(test) ).as_object(); // (1); notice explicit constructor
        auto test2 = value_to<char>(test_new["value"]);
        printf("%d\n",test2);
        return 0;
}
```

**Comment by grisumbras** [comment]
Seems like `160` is outside of the domain of your implmentation's `char`. This implies, that your char is signed and has the domain [-128;127].

**Comment by DUOLabs333** [comment]
Oh --- as it turns out, the previous library I used (nlohmann) silently failed, so I didn't notice that this was an issue.

**Comment by DUOLabs333** [comment]
Is there a way to get the same behavior and ignore the exception (I'm OK with the values wrapping around).

**Comment by grisumbras** [comment]
If you actually have a more complex structure, where the char is deep inside another object, you would have to use contextual conversions. See an example here: https://godbolt.org/z/TK4dhWPEr

**Comment by DUOLabs333** [comment]
Thanks!
