### ISSUE TITLE
Small help for non eagle eyed people

### ISSUE THREAD

**Issue by RoyBellingan** [boostorg/json#976]
In 

https://github.com/boostorg/json/blob/db92f8c22360990f450fe27b86ea1a5830b5cf05/include/boost/json/detail/value_to.hpp#L404

Is possible to add 
```CPP
static_assert(std::is_default_constructible<T>::value, "The destination type must be default constructible");
```

As the error generated contains quite a lot of cruft ? And this should help a bit.

**Comment by grisumbras** [comment]
Alternatively, I should have made default constructibility a requirement for is_described_class.

**Comment by grisumbras** [comment]
Actually, no, I should indeed use a static assert.
